### ISSUE TITLE
build a mobile wallet

### ISSUE THREAD

**Issue by dvc94ch** [Analog-Labs/chain-connectors#6]
- [x] dashboard
- [x] send/recv
- [x] handle intermitten connector connectivity and display status
- [x] create/recover account
- [ ] signer mode
- [x] account transaction history
