### ISSUE TITLE
Ethereum Connector

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/chain-connectors#76]
Endpoints: 
- [x] Block
- [x] Block tx
- [x] Call

--

- [x] Indexer
- [x] Construction API refactor
    - [x] low-level interfaces: Data construction API modified to (Chain specific)
    - [x] high-level interfaces: Wallet API

--

- [x] Contract send calls
- [x] Proofs for Data (Ethereum)
- [x] Release 
     - [x] Deployment & Testing 
     - [x] Documentation
- [x] Patches
