### ISSUE TITLE
Bitcoin Connector

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/chain-connectors#77]
- [ ] - Construction API refactor: Metadata + submit call

- [ ] -- low-level interfaces: Data construction API modified to  (Chain specific)

- [x] -- high-level interfaces: Wallet API

- [ ] - Building transactions (library)
- [x] - Replace construction API
