### ISSUE TITLE
Reorganization of Docker images

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/chain-connectors#78]
- [x] - Indexer+connector container (Ethereum, Polkadot) 
- [ ] - Node container- Indexer+connector container (Bitcoin Chains) 
- [ ] - Node container (End goal)

![IMG_20230119_122323.jpg](https://images.zenhubusercontent.com/63a148ebb22b967900e515c7/3b578a2b-43e6-4fc1-baf7-155904d0e3f1)
