### ISSUE TITLE
Substrate Connector

### ISSUE THREAD

**Issue by isabellelaususan** [Analog-Labs/chain-connectors#82]
- [x] Arbitrary state call (Query state data) (ETA 3-days)
--
- [x] Release Connector (Substrate)
     - [ ] Proofs for Data (Polkadot)
     - [x] Deployment & Testing
- [x] Patches
